### ISSUE TITLE
Need to parse all the elements in the document

### ISSUE THREAD

**Issue by themhz** [DevExpress-Examples/how-to-use-the-document-iterator-object-to-iterate-over-document-elements-t384347#1]
Hello I am trying to parse all the elements in the document using the code 
CS/DocumentIteratorExample/Form1.cs

However I can't get the list of list items like bullets or pictures. Its seems like everything is a paragraph
Is there a way? am I doing something wrong? 

this is my implementation base on your code

```
        public String scanDocument() {
            Document document = base.srv.Document;
            DocumentIterator iterator = new DocumentIterator(document, true);
            MyVisitor visitor = new MyVisitor();            

            while (iterator.MoveNext()) {
                String test = iterator.Current.Type.ToString();                                              
                if (test.Equals("Text"))
                    visitor.Buffer.Append(test + "=");
                else
                    visitor.Buffer.AppendLine(test);

                iterator.Current.Accept(visitor);

            }                                    
            return visitor.Text;
        }
```

MyVisitor class 

  ```
  public class MyVisitor : DocumentVisitorBase {
        readonly StringBuilder buffer;
        public MyVisitor() { this.buffer = new StringBuilder(); }
        public StringBuilder Buffer { get { return buffer; } }
        public string Text { get { return Buffer.ToString(); } }

        public override void Visit(DocumentText text) {
            string prefix = (text.TextProperties.FontBold) ? "**" : "";
            Buffer.Append(prefix);
            Buffer.AppendLine(text.Text);
            Buffer.Append(prefix);
        }
        public override void Visit(DocumentParagraphEnd paragraphEnd) {
            Buffer.AppendLine();
        }
    }
```

**Comment by YuliaDX** [comment]
Hello,

Please accept our apologies for the delayed response. We recommend using our [Support Center](https://supportcenter.devexpress.com/) for asking technical questions. This is the most efficient way to contact our R&D team.

Yes, numbered and bullet lists in RichEditControl's document are represented by paragraphs. Please refer to the following help topic for clarification: [Lists in Rich Text Documents](https://docs.devexpress.com/WindowsForms/9554/controls-and-libraries/rich-text-editor/rich-edit-control-document/lists).

To accomplish this task, override the DocumentVisitorBase.Visit(DocumentParagraphStart) method, use [DocumentParagraphStart.ParagraphProperties](https://docs.devexpress.com/OfficeFileAPI/DevExpress.XtraRichEdit.API.Native.DocumentParagraphStart.ParagraphProperties) to access paragraph properties, and check the [ListLevel](https://docs.devexpress.com/OfficeFileAPI/DevExpress.XtraRichEdit.API.Native.ReadOnlyParagraphPropertiesBase.ListLevel) and [NumberingListIndex](https://docs.devexpress.com/OfficeFileAPI/DevExpress.XtraRichEdit.API.Native.ReadOnlyParagraphPropertiesBase.NumberingListIndex) property values to determine if this paragraph belongs to a numbered or bulleted list.

I recommend you review the following support tickets to get started: 
- [Is it possible to identify bullet list using DocumentIterator?](https://supportcenter.devexpress.com/ticket/details/t824809/is-it-possible-to-identify-bullet-list-using-documentiterator)
- [How to distinguish a bullet list from other lists in a custom DocumentVisitor](https://supportcenter.devexpress.com/ticket/details/t852830/how-to-distinguish-a-bullet-list-from-other-lists-in-a-custom-documentvisitor )
